### ISSUE TITLE
Disable autocomplete in comments and strings

### ISSUE THREAD

**Issue by dmaksimovic** [atom/autocomplete-plus#1006]
It is incredibly irritating to have the autocomplete pop up for every key stroke while I'm typing a simple string inside quotation. It is free human text I want to type, I don't need it autocompleted.

It should be a simple setting, <Turn off for text & comments>, I don't need to be an Atom expert to write my own providers and search for scope names in order to get this turned off.

**Comment by Aerijo** [comment]
I agree that it can be better documented, but adding `.string, .comment` to the scope blacklist will do what you want.

**Comment by delatbabel** [comment]
No that does not work, I have tried it.  Neither .string, nor .comment, nor ".string, .comment" work at all.

I can see that this issue has been around in one form or another since 2015.  In the interim I have disabled autocomplete-plus and will probably end up dropping atom as a result.

**Comment by Aerijo** [comment]
> No that does not work, I have tried it.

I tried it; it does work. If it does not work for you, please fill out the issue template that you deleted when raising the issue, and provide steps to reproduce the issue (what Atom version, what file does it happen for, what language, etc.) We can't fix an issue we can't reproduce.

**Comment by delatbabel** [comment]
I did not raise the issue. Please don't complain to me that I deleted the issue template when I raised the issue, when I did not raise the issue.  Regardless, here is the issue template:

--

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
* Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/ -- the debugging guide says the latest version is 1.8.0 but I currently have 1.32.2
* [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [-] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom -- the issue has been filed multiple times.
* [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Autocomplete can not be turned off in comment lines in the autocomplete-plus package.

### Steps to Reproduce

1. Open a JavaScript file.
2. Commence a comment line by typing "//"
3. Start typing.
4. Note that autocomplete is on.
5. Go to Edit->Preferences->Packages->autocomplete plus
6. Scroll to **Scope Blacklist**
7. Enter the text ".string, .comment" in the scope blacklist box, changing no other settings.
8. Return to editor
9. Start a new line
10. Commence a comment line by typing "//"
11. Note that autocomplete is still enabled.

**Expected behavior:**

Autocomplete should not be enabled on comment lines.

**Actual behavior:** 

Autocomplete is enabled on comment lines.

**Reproduces how often:**

100% of the time.

### Versions  You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

$ atom --version
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

$ apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.2
python 2.7.15rc1
git 2.17.1

Ubuntu version 18.04

### Additional Information  Any additional information, configuration or data that might be necessary to reproduce the issue.

N/A

--

**Comment by Aerijo** [comment]
@delatbabel I believe toggling `Settings -> Core -> Use Tree Sitter Parsers` will patch this issue. It's an obsure side effect of the new grammar system that's been enabled, but should be patched soon now we know about it.

**Comment by delatbabel** [comment]
> @delatbabel I believe toggling `Settings -> Core -> Use Tree Sitter Parsers` will patch this issue. It's an obsure side effect of the new grammar system that's been enabled, but should be patched soon now we know about it.

That does in fact resolve the problem.  How are new users able to find out about this setting, it's really not very obvious?

**Comment by dmaksimovic** [comment]
In the mean time OP (me) has happily avoided filling templates and trying
obscure settings and now happily uses VS Code. Signing off from here, good
luck!

**Comment by SaganRitual** [comment]
Sorry to be totally dense; I just installed Atom today, and adding `.string, .comment` to the Scope Blacklist in the Autocomplete Plus settings does not have the desired effect. I see that turning off autocomplete or tree-sitter is suggested here, but it sounds like that was a temp workaround? I'll disable it, sure, but that turns off **all** the autocompletion 😥

**Comment by 73** [comment]
I just stumbled across this issue. It does wort as described for Python. 
@SaganRitual don't just toggle. Enable:

1. *Enable* the package `autocomplete-plus`
2. *Enable* `Settings -> Core -> Use Tree Sitter Parsers`
3. Go to the settings of `autocomplete-plus` and "Scope Blacklist". Insert to the field: `.string, .comment`.

What language are you using?

**Comment by SaganRitual** [comment]
@73 Works great! Using Javascript atm, but kind of trying to get used to Atom for other languages too, like Swift. Thanks much!
