### ISSUE TITLE
There are times when complementation is not performed when selecting the candidate with tab

### ISSUE THREAD

**Issue by kiiiit** [atom/autocomplete-plus#1025]
### Steps to Reproduce

1. [First Step]
Write Javascript in script tag in HTML file.

2. [Second Step]
When the autocomplete-plus suggestion is displayed, use the tab key to determine the completion candidate.

**Expected behavior:** [What you expect to happen]
Complemented by the selected candidate.

**Actual behavior:** [What actually happens]
Not complemented with a certain probability.

_[Movie]_
https://nimb.ws/ny9L4Z

*Edit by @rsese to add a GIF of the video 📽*

![ac-issue](https://user-images.githubusercontent.com/734194/55540773-433b9f80-5689-11e9-9ed8-5c7e40206a07.gif)

**Reproduces how often:** [What percentage of the time does it reproduce?]
About 50%

### Versions
Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.1
python 3.6.5
git 2.17.2

Macbook pro
MacOs Mojave 10.14.3

**Comment by rsese** [comment]
Thanks for the report!  It looks like the `Prerequisites` section was removed - can you confirm if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by kiiiit** [comment]
thank you for your comment
It did not reproduce in safe mode.

**Comment by rsese** [comment]
Thanks for confirming :+1:  If there's no problem in safe mode, then that likely means a community package is causing the issue:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

You can disable each community package one by one to try and pinpoint which is causing the problem.

It may be that there is still a bug in Atom but if so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
