### ISSUE TITLE
auto-complete packages (all of them including html, css and plus) doesn't work 

### ISSUE THREAD

**Issue by arashderakhshan** [atom/autocomplete-plus#1030]
auto-complete packages (all of them including html, css and plus) doesn't work , and my atom is new and updated. I appreciated if you guide me through enabling those packages.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

In particular, please let us know exact steps to reproduce the problem and what you expect vs. what happens.  For example, what are you typing when you expect autocomplete suggestions?

Please be specific as possible and we'll take a look with you.

**Comment by Aerijo** [comment]
@arashderakshan In particular, you haven’t even told us what you are doing, what you are expecting, and what actually happens.
