### ISSUE TITLE
Filter for Objects(properties) and methods (functions)

### ISSUE THREAD

**Issue by MentalGear** [atom/autocomplete-plus#1055]
It's hard to just browse a huge suggestions list. It would be great if we could filter them based on property or method at least, or even expand the list to inspect more closely.

**Comment by rsese** [comment]
Just following up here - I can see how useful that could be, we'll share your feedback with the other maintainers.  But as mentioned in the issue template, we're not prioritizing new functionality at the moment; we'll close this out since it's not something the team will work on right now but thanks again for the suggestion.

As a side note, please fill out the issue template when opening issues - the information and format of the template is super helpful for us when triaging issues.
