### ISSUE TITLE
Its possible to enable html autocompletion in .md files?

### ISSUE THREAD

**Issue by filipemosca** [atom/autocomplete-plus#1061]
Hi! I write blog posts in markdown but sometimes I need to add html elements. And that simple task became very laborious because I couldn't find any way to enable autocompletion in markdown files.

I know that I can change the grammar file but doing this, I lose the markdown language highlight and interactivity.

Is possible to enable html autocomplete in markdown files?

Thanks a lot!

**Comment by rsese** [comment]
Thanks for reaching out!

I don't believe this is possible with Atom by default (i.e. without installing a community package) but see https://discuss.atom.io/t/can-you-set-multiple-grammar-autocomplete-rules-for-a-filetype/30434 for a previous discussion.  And as mentioned below, you can reach out on the Atom Slack or the message board if you have questions.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
