### ISSUE TITLE
Minimum Word Length setting has misleading description

### ISSUE THREAD

**Issue by dmnd** [atom/autocomplete-plus#335]
The description for the `minimumWordLength` setting says "Only autocomplete when you've typed at least this many characters". I tried to set this above 1 because I find autocomplete way too eager to suggest something. But it doesn't seem to work. I still get suggestions after typing one character. 

So I looked at the source code and it seems that the only use of `minimumWordLength` is to exclude short words from the word list. Which is a completely different thing.

**Comment by benogle** [comment]
Ah strange, I thought it was the same. Tis a bug

**Comment by xeron** [comment]
I run into this issue as well. Is there any way to increase number of characters to type before triggering autocomplete?

**Comment by jcw** [comment]
+1

The main surprise I constantly keep running into is when typing numbers, typing a single digit (such as when tweaking a value) and then using the up or down arrow often ends up in the suggestion list, while I just want to "move on" to another change. Increasing "Delay Before Suggestions Are Shown" mitigates this a bit, but not entirely. Or perhaps numbers, at least small ones, should not be suggestions?

**Comment by yaph** [comment]
@xeron as a workaround you can increase the "Delay Before Suggestions Are Shown" until this gets fixed.

**Comment by sadovnychyi** [comment]
While its possible to read this config value from the autocomplete provider and limit it on the provider side, we shouldn't do it, right?

**Comment by benogle** [comment]
Nah, dont use this setting. We should create a new setting. Not sure about the best naming at this time.

**Comment by muppetjones** [comment]
In essence, the two interpretations of 'Minimum word length' are the same thing. The only benefit to the current implementation is typing 's' instead of 'sup' for 'super-cal-fragilistic-ickspy-alidocious'. However, if you have a variable called `sup` (or any other `s` variable followed by any letter 'a' through 't') and `Minimum word length=3`, you would need to either type `supe` or use the arrow keys to select the longer option, which negates any benefit from predicting at one letter.

Plus, no matter how efficiently you code (which `autocomplete-plus` works pretty quickly--props to you), the number of predictions available will be significantly diminished if you change the number of characters required to yield predictions (you could in fact still work on the predictions before the minimum is met, of course).

Another solution would be to require a single character before predictions are made, or blacklist other characters, e.g., whitespace or `[]{}()=<>`. It is exceedingly rare (I think) for any variable to start with punctuation, other than `_`, `.`, or `$`, in any language. If you're using a tree (which seems likely), you could just add the blacklist characters as leaves so they match no predictions, but you wouldn't have to check for them manually.

**Comment by Slaedr** [comment]
I'm facing this issue as well. A fix would be nice.

**Comment by muppetjones** [comment]
I disabled `autocomplete-python` because it was annoying the crap out of me, switched to `autocomplete-python-plus-jedi` and then disabled it for the same reason. 

Then I noticed that I was no longer getting predictions with less than the minimum character setting. Amazing! Unfortunately, I don't get the python autocomplete, but I don't have to worry about hitting `enter` and having a whole bunch of crap inserted.

**Comment by antcodd** [comment]
I have been taking a look at this issue as part of trying to clean up some day-to-day usability issues and have some thoughts.

The trivial 'fix' would be to not trigger `@getSuggestionsFromProviders` on non-manual suggestion if default `getPrefix` returns a length less than `minimumWordLength`. Actually triggering the suggestion lookup may be useful in some situations however.

I am starting to think it might make more sense for this to be implemented in each provider after all:
1) Always using default `prefix` may not make sense for some languages, even if it includes common dereference operators. Using `replacementPrefix` may also not make sense such as if only part of the text is replaced.
2) Providers should be able to manually complete on dereference operators like `.` and `->`. These are different in different languages. These could alternatively be registered by the provider.
3) Providers can use #463 to behave differently on manual complete (such as not enforcing a minimum completion length depending on performance overhead).

The disadvantage of this is it would not necessarily behave sensibly with multiple completion providers unless they all implemented the feature. Another option would be to give providers the ability to force display of the popup.

**Comment by nmote** [comment]
@antcodd I think you raise some good points, but from an end-user's point of view I think it is still valuable for it to be centrally configurable in one package. Perhaps a good compromise would be to add a `globalMinimumWordLength` setting, but allow providers to override it if they want to do handle prefixes themselves?

**Comment by nmote** [comment]
FYI I am willing to build this if such a PR is likely to be merged.

**Comment by benogle** [comment]
So the symbol provider (now the default) uses the setting in a correct way. External providers can use this setting as well, but it depends on their use case. I think the clarification happening in #593 is sufficient to close this issue.

**Comment by nmote** [comment]
So the official recommendation is for providers to read this setting and then filter themselves based on it?

The two issues I have with that are that:
1. It requires every provider to re-implement the logic that checks the prefix (admittedly not a ton of code, but it's still a few more lines of boilerplate).
2. I think 3 is too high of a default for most providers. While I do think it's a good default for the built-in provider (which would often otherwise have a lot of results), 0 or 1 would be better for many providers such as the one for Flow, which I maintain.

As it stands now, I would just add a setting in the Flow autocomplete provider to change this as a one-off. It would be nicer if we could solve this for everyone.

**Comment by mafflin** [comment]
+1
Faced the same bug.
