### ISSUE TITLE
Bundling autocomplete-plus in core

### ISSUE THREAD

**Issue by benogle** [atom/autocomplete-plus#351]
My goal is only to bundle autocomplete-plus when it gets a lot of little details right. It's pretty close.

For the blog post, I want it to be super user focused, with only a couple pointers to API related things. My goal is to make this a little splashy: "Here are the things showing how much better autocomplete is!". Here's what I want to showcase:

* SymbolProvider showing good suggestion type inference for a couple common languages as the default
  * We can explain how the provider uses the language packages, and point to a docs to make them better
* Working with css, snippets, html and atom APIs is really good
* One or more community providers that work and look awesome
* Pointer to the provider API, and a couple examples

### We will bundle

* autocomplete-plus
* autocomplete-snippets
* autocomplete-css
* autocomplete-html
* autocomplete-atom-api
* autocomplete-emoji (if it exists!)

### Must haves

This is roughly the order I planned to do them in.

* [x] Get one or two (or all?!?) community providers using the suggestion types and left labels
  * cc @basarat @tinloaf @tststs Halp?
* [x] Get all the bundled syntax themes to implement the color vars cc @simurai
* [x] Startup performance eval https://github.com/atom-community/autocomplete-plus/pull/442
* [x] Running performance eval https://github.com/atom-community/autocomplete-plus/pull/400
* [x] Fix `suggestionListFollows == Word` to align the prefix with the suggestion text https://github.com/atom-community/autocomplete-plus/pull/362
* [ ] Get SymbolProvider ready for prime time; it should be close, just need to do some more eval
  * [x] Implement changes API that uses includes builtins https://github.com/atom-community/autocomplete-plus/pull/378
  * [x] Do some performance eval + fixing https://github.com/atom-community/autocomplete-plus/pull/390
  * [x] Add specific support to languages, improve in common languages: js, python, rb
  * [ ] I'd like to make this the default very close to when we bundle autocomplete-plus so it's a bit of a nice surprise. https://github.com/atom/autocomplete-plus/pull/445
* [x] Explore using core:move-up / down to cycle through suggestions. cc @nathansobo and @maxbrunsfeld https://github.com/atom-community/autocomplete-plus/pull/381
* [x] Make sure autocomplete-css is at its best
  * Make it trigger on space or automatically after prop name
  * It currently triggers in comments and generally after any space or dot
  * Works well in CSS, LESS, and SCSS
* [x] Make sure autocomplete-html is at its best https://github.com/atom/autocomplete-html/pull/3
* [x] Make autocomplete-atom-api better https://github.com/atom/autocomplete-atom-api/pull/5
  * Use `snippet`, `leftLabel`, and `type`
* [x] Update defaults
  * [x] `confirmCompletion` -> 'tab and enter'
  * [x] `minimumWordLength` -> 3 https://github.com/atom-community/autocomplete-plus/pull/380
  * [x] `backspaceTriggersAutocomplete` -> false
  * [x] `suggestionListFollows` -> Word
* [x] Figure out how best get this into core and move people using autocomplete-plus to the new bundled autocomplete https://github.com/atom/atom/pull/6710

### Nice to haves

* [ ] Unicode support
* [x] Emoji provider for use in markdown + text we can bundle

### Help!

Help is welcome! If you would like to take any of the above tasks, let me know!

Big helps would be:

* Updating your provider to use API 2.0 and all the shiny new features helpful in your situation.
* Making the language packages better
  * Better symbol scopes
    * https://github.com/atom/language-javascript/issues/137 e.g. js language doesnt tag functions as functions.
    * https://github.com/atom/language-coffee-script/issues/53 e.g. coffee language doesnt tag many variables.
  * Defining all the builtins in your fav language
    * We may be able to specify them in a richer manner than just strings. See https://github.com/atom-community/autocomplete-plus/wiki/SymbolProvider-Config-API
  * Adding the config for the SymbolProvider to your language
    * See https://github.com/atom-community/autocomplete-plus/wiki/SymbolProvider-Config-API for docs
* Add unicode support
* ~~OMG write autocomplete-emoji @lee-dohm :rocket: :heart:~~

**Comment by joefitzgerald** [comment]
On the topic of emojis: https://atom.io/packages/autocomplete-emojis / https://github.com/eqot/autocomplete-emojis (hi @eqot!).

**Comment by basarat** [comment]
> using the suggestion types and left labels

I don't know what is `suggestionType` or `leftLabel` : https://github.com/atom-community/autocomplete-plus/wiki/Provider-API#suggestions

**Comment by joefitzgerald** [comment]
@basarat that wiki page needs to be updated. @benogle made significant changes in #334 that introduced new properties.

**Comment by basarat** [comment]
Updated :+1: https://github.com/atom-community/autocomplete-plus/wiki/Provider-API#suggestions

**Comment by basarat** [comment]
After much headbanging, I realize `type` and `leftLabel` is not shipped yet :) Is it?

**Comment by joefitzgerald** [comment]
Not yet, but it's an `apm publish minor` away from being released: https://github.com/atom-community/autocomplete-plus/commits/master (it's merged to master).

**Comment by basarat** [comment]
@joefitzgerald cool. Ping me when done :heart:

**Comment by basarat** [comment]
Also I provide autocomplete for `path` as well, doesn't have a default mapping : https://github.com/atom-community/autocomplete-plus/pull/334#issuecomment-85697409

**Comment by joefitzgerald** [comment]
> Update defaults
> `backspaceTriggersAutocomplete` -> false

:-1: because backspacing can be seen as a way to "un-refine" the suggestion list. In the current bundled autocomplete, backspacing un-refines the suggestion list but it's done in the built-in input - which isn't present anymore here.

If backspacing isn't enabled by default, a single mistaken keystroke will then result in two more actions (backspace, then trigger autocomplete). If it is enabled, there is a frictionless interaction.

Providers can choose to suppress autocomplete on backspace, and you could also choose to suppress a suggestion request if the entire line is whitespace as a result of the backspace.

**Comment by tinloaf** [comment]
Can you provide documentation on how to use the suggestion types and left labels? As soon as an API is defined and stable, I'm happy to adapt my python-plugin to it ;)

**Comment by basarat** [comment]
> Give me a day.

wait for it to be published before you start the work :+1:

**Comment by joefitzgerald** [comment]
> Figure out how best get this into core and move people using autocomplete-plus to the new bundled autocomplete

As far as I can tell there are two distinct paths (replace `autocomplete-plus` with `autocomplete-snippets` or `autocomplete-paths`, as necessary):

1. Transfer `autocomplete-plus` to the https://github.com/atom organization
  - [ ] :phone: @thedaniel and get him to do his fun little database hack that fixes the registration for https://atom.io/packages/autocomplete-plus
  - [ ] Deprecate / remove https://github.com/atom/autocomplete
  - [ ] Done
1. Create a PR from `autocomplete-plus` back to https://github.com/atom/autocomplete
  - [ ] Determine if you want to actually create a clean PR or one that clobbers history
  - [ ] Create feature branch
  - [ ] Resolve all merge conflicts, verify the integrity of autocomplete-plus, tests
  - [ ] Create PR to https://github.com/atom/autocomplete
  - [ ] Merge PR
  - [ ] Create feature branch to remove all autocomplete-plus code and logic, leaving an 'empty' package with package.json so that it can be released
  - [ ] Merge feature branch for emptying autocomplete-plus
  - [ ] Release "emptied" autocomplete-plus
  - [ ] Release autocomplete
  - [ ] :arrow_up: autocomplete at https://github.com/atom/autocomplete
  - [ ] Release atom
  - [ ] Optionally include code for atom that disables / uninstalls autocomplete-plus
  - [ ] Done

**Comment by thedaniel** [comment]
>  get [me] to do his fun little database hack that fixes the registration for

We store numeric repo IDs now so it will probably Just Work. Don't quote me on that though, it's been a minute since I looked at that code ;)

**Comment by tinloaf** [comment]
> wait for it to be published before you start the work :+1:

Nah. Let's get this done. It's kinda hard to map what Jedi is giving me to the predefined classes though.

**Comment by joefitzgerald** [comment]
@benogle are we effectively suggesting that most providers should use `leftLabel` to represent one of:

* information about the type of the suggestion (i.e. an elaboration of the type / icon to the left)
* information about what the suggestion "returns" (this would be used instead of the former)

If so, what should we advise people is the purpose of rightLabel? I'd like to communicate contextual intent of each on the wiki page to ensure provider authors understand how to decide when to use each, and what to include in each.

In converting go-plus to use the type correctly, I've identified a potential optimization, which is best illustrated by an example:

* gocode (a go autocomplete engine) emits suggestions whose types can be `func`, `package`, `var`, `type`, `const`, `PANIC`
* all map cleanly to existing syntax-color variables (panic is discarded), however `package` maps to `import` or `require`
* if I map `package` to `import`, the icon is `i`, and is colored correctly - but in leftLabel I have `package`, which is weird looking ("why does that icon say `i`"?) 
* if I map `package` to `require`, the icon is `r`, and is colored correctly - but in leftLabel I have `package`, which is weird looking ("why does that icon say `r`"?) 
* if I don't map `package`, the icon is `p`, and is colored incorrectly
* if I add  `.make-type-icon(package, @syntax-color-import);` to `autocomplete.less`, everything is hunky-dory

It sure would be nice to be able to achieve `p` as the icon, with a mapping of `package` to `import`. Or to be able to achieve the make-type-icon mapping without having to modify a stylesheet.

Thoughts?

**Comment by joefitzgerald** [comment]
For what it's worth, it was the right decision to go with the type icon and leftLabel - it's nice and clean (ignoring my theme for a moment):

![screen shot 2015-04-02 at 11 24 24 pm](https://cloud.githubusercontent.com/assets/744740/6978410/98b37d5a-d98f-11e4-96d4-02ad6244659d.png)

**Comment by joefitzgerald** [comment]
@basarat @tinloaf icon/leftLabel is published in `v2.8.0`. I've also released `go-plus` `v3.3.4` making use of it.

**Comment by basarat** [comment]
![image](https://cloud.githubusercontent.com/assets/874898/6978658/c3298fdc-da22-11e4-9705-a2a9be6c60f2.png)
*slick*. I love you guys :rose: `atom-typescript` :ship:ed.

**Comment by joefitzgerald** [comment]
@basarat try moving your rightLabel content to leftLabel. And surrender styling of it to autocomplete-plus, just as an experiment. I think you'll find it cleaner.

**Comment by joefitzgerald** [comment]
Oh one other thing @basarat you can easily turn `importScripts` into an anonymous snippet. In this scenario, you'd have `void` in `leftLabel`, and emit a snippet that looks something like: `importScripts(${1:...urls: string[]})`. It'll be much shorter to display.

**Comment by abe33** [comment]
Just catching up. This is indeed a great news. :clap: 

If possible, I would like to see in the :ship:ed documentation a working example of how to test a provider in real conditions (with editor and all). 
I was using `autocomplete-snippets` specs as working sample, but v2.8.0 broke something and my specs no longer passes. It seems the autocomplete list no longer append returned suggestions when `displaySuggestions` have been called (in test mode).

**Comment by joefitzgerald** [comment]
@abe33 I'd help if you included a link to a branch or some commits.

**Comment by benogle** [comment]
> It's kinda hard to map what Jedi is giving me to the predefined classes though.

@tinloaf what is it giving you that is difficult to map? To all y'all mapping items to these types, please list the ones you are having trouble with. The list is definitely not set in stone. 

> re: leftLabel ... information about what the suggestion "returns" (this would be used instead of the former)

Yes. It is for return values. Anything else should be in the `rightLabel`.

> On the topic of emojis: https://atom.io/packages/autocomplete-emojis / https://github.com/eqot/autocomplete-emojis (hi @eqot!).

Yeah, but it doesnt inject actual emojis. I want to use something like [this DB](https://github.com/github/gemoji/blob/master/db/emoji.json) to insert actual emojis

> if I add .make-type-icon(package, @syntax-color-import); to autocomplete.less, everything is hunky-dory

This is probably fine in the autocomplete less. We should use the [package](https://octicons.github.com/icon/package/) icon for these types. It should just be a few entries in [this dict](https://github.com/atom-community/autocomplete-plus/blob/master/lib/suggestion-list-element.coffee#L15) to add the icon.

![image](https://cloud.githubusercontent.com/assets/874898/6978658/c3298fdc-da22-11e4-9705-a2a9be6c60f2.png)

@basarat Echoing @joefitzgerald, I would do a few things here: 

* Remove the snippet completion, and leave it to autocomplete-snippets
* For `importScripts`, use `{type: 'function', leftLabel: 'void', snippet: 'importScripts(${1:urls...:string[]})'}`
* For the interfaces, use `{type: 'type'}`
* Dont use any right labels in this case.

> If possible, I would like to see in the shipped documentation a working example of how to test a provider in real conditions (with editor and all).

Noted. This can definitely be cleaned up in our current tests.

Thanks guys for digging in. I'm out til monday, so I cant do any real work until then.

**Comment by joefitzgerald** [comment]
> Yes. It is for return values. Anything else should be in the rightLabel.

I would expand that statement slightly:

> * `leftLabel`:
>   * If a suggestion has a `type` of `function` (or a conceptual equivalent, like `method`), `leftLabel` should be used to describe the return value of the text or snippet that the suggestion pertains to
>    * For any other suggestion `type`, `leftLabel` can be used to further describe the type (e.g. if type is `constant`, `leftLabel` might be `const`)

**Comment by joefitzgerald** [comment]
> [...] so it will probably Just Work. Don't quote me on that though [...]

Well I've quoted you now, so I expect it to work :laughing:.

**Comment by abe33** [comment]
@joefitzgerald Solved, it was because the tests were relying on removed classnames to retrieve the test elements.

**Comment by basarat** [comment]
I didn't know about `autocomplete-snippets`, so thanks! . However it does not work with `atom-typescript` : https://github.com/atom-community/autocomplete-snippets/issues/46

**Comment by basarat** [comment]
Also: 

> For importScripts, use {type: 'function', leftLabel: 'void', snippet: 'importScripts(${1:urls...:string[]})'}

It gets hairy, functions have overloads, (some have 105 e.g. the `on` handler). We don't list them all, The process is two step, complete function by name, Second step: we provide the signatures for completion: 

![image](https://cloud.githubusercontent.com/assets/874898/6990801/c29b5872-dac0-11e4-8093-5a22869ffc95.png)


> For the interfaces, use {type: 'type'}

Done :)

> Dont use any right labels in this case. 

No, because I'd like to like to show `interface` `type` differently (all map to `type`). The right label shows that difference.

**Comment by joefitzgerald** [comment]
But the stuff in rightLabel in leftLabel instead.

**Comment by basarat** [comment]
> Put the stuff in rightLabel in leftLabel instead.

I've moved some of it (e.g. `function` / `method` is only on the left). But still left some of it duplicated (`class` / `interface`)  since I like to have these colors on the right (sorry): 

![image](https://cloud.githubusercontent.com/assets/874898/6991344/7bd42472-dada-11e4-93e6-7a0c484462e2.png)

**Comment by joefitzgerald** [comment]
This could come off the wrong way, but you should embrace the convention and avoid doing styling that is custom for your provider. In this particular case, the styling doesn't seem to add value

We should let theme authors handle styling of the suggestion list.

**Comment by joefitzgerald** [comment]
I suppose another way to state what I'm trying to convey is:

If the user cannot (visually) tell the difference between different providers' suggestions (because they are visually consistent), then we've all collectively done the right thing.

Colorization of each 'type' of suggestion is driven by syntax themes; styling of the suggestion list can be modified by theme authors. Provider authors should try to refrain from "theming" the list, and instead should ensure that their suggestions are semantically and contextually correct.

**Comment by benogle** [comment]
@basarat please place the return type in the left label. As joe said, the
suggestion type is handled by the little icon. If you'd like, we can add an
'interface' type so you are not using 'type'.

Echoing joe, provider uniformity is important because the user does not
know where one provider ends and the other starts.

**Comment by eqot** [comment]
@benogle, do you mean [autocomplete-unicode-emojis](https://github.com/eqot/autocomplete-unicode-emojis)?

![autocomplete-unicode-emojis](https://dl.dropboxusercontent.com/u/972960/Documents/atom/atom-autocomplete-unicode-emojis/autocomplete-unicode-emojis.gif)

This package is just quickly developed and has not been published as an atom package yet.

**Comment by tinloaf** [comment]
@benogle My python-jedi provider does now support the type icons. I'm not sure if I will support the left label, since return types can most of the time not be inferred in a dynamically typed language like python, and so 90% of the time this will just read "value"...

**Comment by tinloaf** [comment]
@benogle By the way - when bundling ACP in core, will the providers just magically work? What about the "old" autocomplete providers, do they stop working? Or do I have to move my autocomplete-plus provider to an autocomplete provider? Or will both be working in tandem? So many questions...

**Comment by tststs** [comment]
Looking good so far.

![bildschirmfoto 2015-04-06 um 17 18 00](https://cloud.githubusercontent.com/assets/3591665/7006431/62cc4114-dc81-11e4-94e9-eaebfc6df733.png)

But it is pretty hard to determine the (icon)-type of every suggestion with tern, cause only ```isKeyword```is passed. fn(..) resolves to function and all the rest at the moment is just variable :)

Keep up the good work! :rocket:

**Comment by benogle** [comment]
> @benogle, do you mean autocomplete-unicode-emojis?

Awesome. I have some suggestions, will make issues!

> I'm not sure if I will support the left label

That's ok, no prob. It's definitely going to be better on statically typed languages.

> when bundling ACP in core, will the providers just magically work? What about the "old" autocomplete providers, do they stop working? Or do I have to move my autocomplete-plus provider to an autocomplete provider? Or will both be working in tandem? So many questions...

Yes, they should just magically work. All the providers provide a `autocomplete.provider` service, which the new bundled autocomplete will consume, so everything should Just Work.

> ![bildschirmfoto 2015-04-06 um 17 18 00](https://cloud.githubusercontent.com/assets/3591665/7006431/62cc4114-dc81-11e4-94e9-eaebfc6df733.png)

Are you guys(@tststs, @basarat) super against using the `snippet` field instead of the huge right label with all the types? That right label is invisible immediately when the user selects a suggestion, and the arg types might be hard to remember after the list goes away. If you use the `snippet`, they can tab between the arguments.

**Comment by benogle** [comment]
> As far as I can tell there are two distinct paths (replace autocomplete-plus with autocomplete-snippets or autocomplete-paths, as necessary):

@joefitzgerald, I like option 2 you outlined for upgrading. The empty autocomplete-plus could even disable or remove itself. Not sure.

**Comment by tststs** [comment]
> Are you guys(@tststs, @basarat) super against using the snippet field instead of the huge right label with all the types? That right label is invisible immediately when the user selects a suggestion, and the arg types might be hard to remember after the list goes away. If you use the snippet, they can tab between the arguments.

@benogle, not against the ```snippet``` field, but just not ready yet. :)
And for myself i don't like snippets that being passed to the editor. In most cases, i don't need all the params provided (optional params).

So i made this:
![687474703a2f2f7777772e746f626961732d73636875626572742e636f6d2f6769746875622f6769746875622d61746f6d2d7465726e6a732d696e6c696e652d322e706e67](https://cloud.githubusercontent.com/assets/3591665/7018250/460a3122-dd02-11e4-88e5-319da0d53dac.png)

**Comment by eqot** [comment]
@benogle, thank you very much for the clarification and the issues.
I wanted to check if it is exactly what you mean before polishing its usability. I will fix the issues shortly.

**Comment by eqot** [comment]
>    minimumWordLength -> 3

@benogle, this default would be a problem in [autocomplete-unicode-emojis](https://github.com/eqot/autocomplete-unicode-emojis) to show :+1: by typing ':+', for example. 2 is better, hopefully.
Or, is it possible to overwrite ``minimumWordLength`` in each autocomplete package?

**Comment by benogle** [comment]
> Or, is it possible to overwrite minimumWordLength in each autocomplete package?

Each provider should be adhering to this option, so the emoji provider can simply ignore it.

**Comment by tststs** [comment]
Ok, removed ```rightLabel``` and using ```snippet``` from now on :)

![bildschirmfoto 2015-04-07 um 22 23 20](https://cloud.githubusercontent.com/assets/3591665/7032757/25250f72-dd75-11e4-951e-79c0f99b3964.png)

**Comment by benogle** [comment]
Nice :+1: Do you know the return values of the functions?

**Comment by tststs** [comment]
yes. just a bad screenshot-example here :)

![bildschirmfoto 2015-04-07 um 23 03 37](https://cloud.githubusercontent.com/assets/3591665/7033490/9c432d1e-dd7a-11e4-83b6-a1c0204aa094.png)

**Comment by benogle** [comment]
Amaze

**Comment by eqot** [comment]
> Each provider should be adhering to this option, so the emoji provider can simply ignore it.

Glad to hear that. Thank you for the information!

**Comment by joefitzgerald** [comment]
> The empty autocomplete-plus could even disable or remove itself. Not sure.

@benogle I'd prefer to find a way to 'clean up' autocomplete-plus by having it remove itself once it's in that state. I'm unsure as to how atom feels about a package removing itself. Will bad things happen, as files are in use, and those files are being deleted?

**Comment by mehcode** [comment]
Just wanted to ask if disabling autocomplete while in a comment (perhaps on a provider by provider basis) was on the immediate roadmap? Just something that can be frustrating at the moment.

**Comment by benogle** [comment]
@mehcode, you can set the `Scope blacklist` setting in the autocomplete-plus settings to `.comment` to disable in comments.

**Comment by mehcode** [comment]
Awesome! That works nicely.

Some providers might want to work inside comments (perhaps emoji?). Just a thought to consider. 

Also can we make that setting default somewhere along the way to 1.0?

**Comment by thedaniel** [comment]
> Also can we make that setting default somewhere along the way to 1.0?

I also think this is a great idea.

**Comment by maxbrunsfeld** [comment]
> Also can we make that setting default somewhere along the way to 1.0?

I agree. I would add that strings should be added too if possible.

**Comment by joefitzgerald** [comment]
I disagree. The moment you disable comments by default in the package is the moment you effectively make any provider that does want to work and do something novel in comments infeasible. 

Each provider can choose to suppress a suggestion request to themselves, and each should do so in comments (like go-plus does) if autocomplete doesn't make sense in comments for that grammar / context.

**Comment by thedaniel** [comment]
> The moment you disable comments by default in the package is the moment you effectively make any provider that does want to work and do something novel in comments infeasible.

This is pretty dramatic considering the setting can be changed.

**Comment by joefitzgerald** [comment]
What I'm suggesting @thedaniel is that the settings for _this package_ should be as open and permissive to other providers as possible. Adding stuff to the blacklist default suppresses unforeseen ideas that you and I cannot conceive right now.

The right thing to do is - prior to 1.0 - ensure that all the bundled providers and also all of the community providers (where it makes sense) don't provide suggestions in comments - this has the same net effect, but preserves the possibility for future innovation inside comments (or other selector(s) - this is a slippery slope).

**Comment by maxbrunsfeld** [comment]
@joefitzgerald but whether to provide completions in comments can't just be up to the package. The user needs a way to configure it. Are you saying that each provider should have a *separate* setting for disabling completions in particular scopes?

This seems like a worse user experience than disabling it for comments globally.

**Comment by joefitzgerald** [comment]
@maxbrunsfeld: the user can always suppress selector(s) globally in the blacklist setting.

I'm suggesting that our collective desire to suppress autocomplete in comments by default is more an expression that we don't wish to see suggestions in comments when there is no contextual benefit from it. Most providers (e.g. mine, go-plus) don't provide useful information in comments so I've disabled it in that scope.

Other providers should choose to do the same. They can choose to do so in a way that is or is not configurable, depending on the context. If you don't make defaults decisions at the provider level you will inevitably get into debates over defaults (e.g. Imagine someone writes a provider for JavaDoc autocomplete in Java files - they will naturally lobby for the default to change. Their users will also scream out for all the providers to suppress suggestion requests *except* for their beloved JavaDoc provider).

We've done multiple things recently to remove the governor on when autocomplete requests are dispatched, to preserve the ability of providers to make sensible decisions about when they should provide suggestions. Changing the default to suppress in comments walks that backwards, and I think it introduces a number of challenges that you're not considering yet.

**Comment by maxbrunsfeld** [comment]
That seems reasonable to me. I think I'd be satisfied as long as the *built-in* completion provider didn't provide completions in comments (or strings, ideally) by default.

**Comment by joefitzgerald** [comment]
> I think I'd be satisfied as long as the built-in completion provider didn't provide completions in comments (or strings, ideally) by default.

:+1: on that.

**Comment by benogle** [comment]
Lets move the discussion about this to https://github.com/atom-community/autocomplete-plus/issues/377

**Comment by eqot** [comment]
Instead of publishing [autocomplete-unicode-emojis](https://github.com/eqot/autocomplete-unicode-emojis) as a package, I have updated [autocomplete-emojis](https://github.com/eqot/autocomplete-emojis) which now supports unicode emojis as well as markdown emojis.

![autocomplete-emojis](https://dl.dropboxusercontent.com/u/972960/Documents/atom/atom-autocomplete-emojis/atom-autocomplete-emojis.gif)

Tricky thing is that there are a lot of suggestions for unicode and markdown emojis, like ```:sm``` shows 49 unicode emojis and 48 markdown emojis. This is quite frustrated if you want to choose markdown emojis from the suggestions.
So,  [autocomplete-emojis](https://github.com/eqot/autocomplete-emojis) also supports ```::``` prefix to show markdown emojis only.

**Comment by benogle** [comment]
Lookin good @eqot :+1:

**Comment by eqot** [comment]
Thanks! :smile:

**Comment by benogle** [comment]
If people are looking to help, improving the language packages would be a big help. Here are two issues for coffee and javascript.

* https://github.com/atom/language-javascript/issues/137
* https://github.com/atom/language-coffee-script/issues/53

Feel free to go deep on your favorite language too. Properly detecting and scoping variables, functions, classes, mixins, etc will make the symbol provider much better.

**Comment by joefitzgerald** [comment]
@benogle What say you on `backspaceTriggersAutocomplete -> false`.

I've disagreed with this on the basis that we should allow any single keystroke to trigger autocomplete (by default), and let the user (via configuration) or the providers (via configuration or not) determine keystrokes for which suggestions should be not provided (e.g. see: https://github.com/joefitzgerald/go-plus/pull/180). Doing otherwise hinders novel use cases that we cannot foresee.

I don't think we're in agreement yet, so what are the arguments for this change?

**Comment by benogle** [comment]
I strongly feel that we should have it disabled by default. I'd like to argue about this in another thread.

**Comment by ctolkien** [comment]
In omnisharp-atom (handling C# autocompletion). We have some styling issues with C# when the description needs to overflow, things aren't floating correctly:

![](http://i.imgur.com/dZpliwM.png)

**Comment by joefitzgerald** [comment]
@ctolkien: might want to weigh in on #405.

**Comment by nathansobo** [comment]
:fireworks:

**Comment by ilanbiala** [comment]
@nathansobo is this going to be shipped with Atom by default now?

**Comment by mnquintana** [comment]
@ilanbiala It's shipping with Atom now as of 0.199.0

**Comment by ctolkien** [comment]
Is there anything we need to specifically handle to migrate? Or can we just yank out the  package dependency and things will "just work".

Ref: https://github.com/OmniSharp/omnisharp-atom/pull/277
