### ISSUE TITLE
Add a config option to disable restrictions when activated manually

### ISSUE THREAD

**Issue by mauricioszabo** [atom/autocomplete-plus#440]
I don't like the AutoComplete popping when I type - I am easily distracted, so I prefer to hit a keystroke to autocomplete.

I discovered that when I activated with my keystroke, it didn't worked as expected - some results I only got when auto-activated. Then I saw the restriction.

Is it possible to add an option in the package, such as we could choose if we want this restriction or not?

**Comment by benogle** [comment]
What restrictions are you seeing when using manual mode? Can you give a detailed list of expected and actual behaviors?

**Comment by mauricioszabo** [comment]
The restrition is mostly this: https://github.com/atom/autocomplete-plus/blob/master/lib/autocomplete-manager.coffee#L184

For instance, if I want to auto-complete the word "FuzzyProvider", I can just type `fuzpr` and it'll autocomplete, but if I activate it manually, to be able to auto-complete I need to type `fuz`, press TAB, then type `pr`.

**Comment by benogle** [comment]
cc @nathansobo

**Comment by nathansobo** [comment]
Previously, I wanted the activation prefix to be strict because I was getting a lot of spurious suggestions in situations where I knew the prefix I wanted explicitly. I never typed a fuzzy match and then manually activated. Now I'm using auto-activation so it doesn't matter to me, personally. Wondering if we should just make the behaviors consistent or provide an option regarding the prefix.

**Comment by benogle** [comment]
@nathansobo i'm tempted just to remove the strict matching

**Comment by nathansobo** [comment]
Go for it.
