### ISSUE TITLE
Return custom select-prev/next commands

### ISSUE THREAD

**Issue by xlaywan** [atom/autocomplete-plus#453]
I found no way how to remap keys like this:
```
'atom-text-editor:not(mini).autocomplete-active':
   'alt-up': 'autocomplete-plus:select-previous'
   'alt-down': 'autocomplete-plus:select-next'
   'alt-enter': 'autocomplete-plus:confirm'
```
But `up`, `down` and `enter` without alt-key to use as usual.

I think that the pullback of this PR (https://github.com/atom/autocomplete-plus/pull/381) should fix this problem.

**Comment by xlaywan** [comment]
Or add `editor:move-cursor-up/down` commands in atom core, but keep going use `core:move-up/down` for this package so I could remap key bindings by `'alt-up/down': 'editor:move-cursor-up/down'`

**Comment by lee-dohm** [comment]
I agree that with @benogle from #381 that, by default, selecting items in the `autocomplete-suggestion-list` should use `core:move-up/down`. But also, that one should be able to use the normal mechanisms for remapping keys to `core:move-up/down` within the `autocomplete-suggestion-list` which does not seem to work currently.

The correct solution seems to me to be to make it possible to remap `core:move-up/down`, which I haven't been able to find a way to do. For example, I tried:

```coffee
'autocomplete-suggestion-list':
  'ctrl-shift-alt-z': 'core:move-down'

'.autocomplete autocomplete-suggestion-list':
  'ctrl-shift-alt-z': 'core:move-down'
```

Neither of them worked. They would show up as the only entry in the Keybinding Resolver, but grey instead of green (active). (The reason why I use such a weird key is I know that nothing else is using it, so I don't have to worry about other things trying to grab it.)

**Comment by jschroeder9000** [comment]
+1 I prefer to use custom keys to navigate the suggestions and not being able to move the cursor normally when suggestions are displayed is pretty frustrating.

**Comment by joefitzgerald** [comment]
Do the instructions at https://github.com/atom/autocomplete-plus#usage not work?:

```cson
'atom-text-editor:not(mini).autocomplete-active':
  'tab': 'unset!'
  'enter': 'autocomplete-plus:confirm'
  'up': 'unset!'
  'down': 'unset!'
  'ctrl-p': 'core:move-up'
  'ctrl-n': 'core:move-down'
```

The key is `'unset!'`.

**Comment by jschroeder9000** [comment]
No, `unset!` does not work for me.  It would seem I'm not alone:

https://discuss.atom.io/t/how-to-disable-arrow-keys-in-autocomplete-plus/16957

**Comment by lee-dohm** [comment]
@joefitzgerald, I added the suggested settings to the `keymap.cson` and it *did* add <kbd>Ctrl+N</kbd> and <kbd>Ctrl+P</kbd>, as expected. The up and down arrow keys still worked, though. I think the unsetting part though is more to do with atom-keymap than autocomplete-plus.

**Comment by xlaywan** [comment]
I resolved it so(thanks @lee-dohm):
`keymap.cson`
``` cson
'atom-text-editor:not([mini]) !important':
   'enter': 'editor:newline'

'atom-text-editor:not(mini).autocomplete-active':
   'alt-up': 'core:move-up'
   'alt-down': 'core:move-down'
   'down': 'my:move-down'
   'up': 'my:move-up'
   'alt-enter': 'autocomplete-plus:confirm'
```

`init.coffee`
``` coffee
atom.commands.add 'atom-text-editor', 'my:move-up', ->
	editor = atom.workspace.getActiveTextEditor()
	atom.commands.dispatch(atom.views.getView(editor), 'autocomplete-plus:cancel')
	atom.commands.dispatch(atom.views.getView(editor), 'core:move-up')

atom.commands.add 'atom-text-editor', 'my:move-down', ->
	editor = atom.workspace.getActiveTextEditor()
	atom.commands.dispatch(atom.views.getView(editor), 'autocomplete-plus:cancel')
	atom.commands.dispatch(atom.views.getView(editor), 'core:move-down')
```

**Comment by benogle** [comment]
Closing as this has been resolved.

**Comment by jschroeder9000** [comment]
I'm skeptical that this issue is truly resolved.  @xlaywan may have have figured out a workaround (apparently thanks to @lee-dohm), but if I'm understanding this correctly the root issue has not been resolved.

I admit that I find the original bug report to be a bit confusing and the OP (@xlaywan) seems reasonably satisfied with a workaround, but if this is the same issue that @lee-dohm [claims it is in the forums](https://discuss.atom.io/t/how-to-disable-arrow-keys-in-autocomplete-plus/16957) (which I think is true) then I don't see how this can possibly be resolved.

The documentation states that keys can be remapped like so:

```
'atom-text-editor:not(mini).autocomplete-active':
  'tab': 'unset!'
  'enter': 'autocomplete-plus:confirm'
  'up': 'unset!'
  'down': 'unset!'
  'ctrl-p': 'core:move-up'
  'ctrl-n': 'core:move-down'
```

But the fact is this does not work; using `unset!` in `keymaps.cson` for `up` and `down` does not affect the current version of `autocomplete-plus`.  So unless I'm grossly misunderstanding this, either the documentation needs to be revised to include something similar to the workaround that @xlaywan posted or the underlying bug needs to be fixed.

@lee-dohm you seem to have a decent grasp on this issue.  Am I way off base here?  Would a new issue be helpful?  Possibly in `atom-keymap` (if that's where the root issue truly lies)?
