### ISSUE TITLE
Disable the default provider initially

### ISSUE THREAD

**Issue by edrex** [atom/autocomplete-plus#484]
Now that Atom ships with this plugin, when I am editing a markdown file or other text, I get this distracting and useless popup at random times during my editing. I think the default provider should be disabled initially, since now there is no "opt-in" step, as there was when this plugin was a manual install.

**Comment by joefitzgerald** [comment]
@edrex Sorry, the default provider won't be disabled by default. But you can easily exclude it from triggering in a markdown file by updating one of the following two preferences:

* `File Blacklist`: `.*, *.md`
* `Scope Blacklist`: `.source.gfm`

Either will suppress autocomplete (along with all autocomplete providers) in a Markdown file.

You can also completely disable the default provider for all files and scopes by unchecking the `Enable Built-In Provider` preference.

**Comment by edrex** [comment]
Autocomplete in prose-oriented document types is useless and distracting.  This is a jarring UI change that every user is going to bump into and dislike. It's your project but this is a major change to the default experience without any apparent thought.

**Comment by joefitzgerald** [comment]
@edrex It's clear you feel passionately about this, and I acknowledge that for some people this may indeed feel like it's a jarring change. Most people have generally perceived the inclusion of autocomplete-plus to be a positive thing. I was simply providing you access to the tools necessary to customize the package for your needs - as every user's needs are going to be slightly different (which is why these configurable options are present!).

Also, this isn't my project, I'm just a contributor to the autocomplete-plus package.

We have talked previously about suppressing the default provider for specific grammars (using the `provider.disableForSelector` property). But disabling the default provider for all filetypes is likely a far worse experience for people expecting some form of autocompletion in files other than markdown (e.g. JavaScript).

**Comment by ricardograca** [comment]
@joefitzgerald I'm using Atom 0.200.0 and the autocomplete-plus package (2.17.0) says that `.source.gfm` is the default for Built-In Provider Blacklist, but there is no default for Scope Blacklist, which causes the popup to appear when editing a markdown file. I have no idea what the difference between the two fields is but shouldn't they both have the same defaults? Or why isn't the Built-In Provider Blacklist doing anything in this case?

**Comment by joefitzgerald** [comment]
@ricardograca Please paste the output of `apm list`, so we can determine if you have other autocomplete providers providing suggestions.

The reason the default scope blacklist is empty is that any defaults here would suppress novel provider use cases that we cannot currently foresee. You can very easily edit that configuration item to suppress any scope you find disruptive (try command-option-p to see the scope(s) at the current cursor position). This will will suppress *all* providers for those scopes (comma delimited) that you specify.

The default provider blacklist suppresses the built-in provider(s), which are only 1 or 2 of a litany of possible providers.

**Comment by ricardograca** [comment]
@joefitzgerald [Here it is](https://gist.github.com/ricardograca/5b876d4880a5fdf64911)

**Comment by TylerTemp** [comment]
@joefitzgerald Where can I edit the `File Blacklist` or `Scope Blacklist` or `Enable Built-In Provider` ? Thanks :)

**Comment by joefitzgerald** [comment]
@TylerTemp `Atom > Preferences > Packages > autocomplete-plus > Settings`
