### ISSUE TITLE
Use fuzzaldrin-plus as an option

### ISSUE THREAD

**Issue by benogle** [atom/autocomplete-plus#586]
Hey @jeancroy we all like the improvements to fuzzy-finder with fuzzaldrin-plus. Would you be down to add it to autocomplete-plus as an option? This might be a bit sticky in the `SymbolProvider` with the [locality scoring](https://github.com/atom/autocomplete-plus/blob/7cca9b663a29d60e3257cb6c446c752a3fc01352/lib/symbol-provider.coffee#L212), but should be doable.

**Comment by jeancroy** [comment]
Ok I'll keep the locality bonus math as-is for now. I have a feeling it'll be a bit less strong that it was previously. Scoring in fuzzaldrin-plus was done such as better match have better score by a lot.

My plan is to keep proximity bonus as it is and see how it goes & collect issues. If external information become important, I may try to compress a bit the scoring scheme. On the other hand, I have a feeling this locality thing exist because on previous fuzzaldrin every result where about as good from a lack of measuring things that could differentiate them.

**Comment by jeancroy** [comment]
Do we want this for the fuzzy provider as well or only symbol ?

**Comment by benogle** [comment]
Just symbol, and the [builtin fuzzy searching](https://github.com/atom/autocomplete-plus/blob/7cca9b663a29d60e3257cb6c446c752a3fc01352/lib/autocomplete-manager.coffee#L222) for providers.

**Comment by jeancroy** [comment]
https://github.com/atom/autocomplete-plus/blob/7cca9b663a29d60e3257cb6c446c752a3fc01352/lib/autocomplete-manager.coffee#L217

Every suggestion has the power to fake the prefix that was entered by the user ?

**Comment by benogle** [comment]
Yes

**Comment by jeancroy** [comment]
Hi @benogle .
How is test of this thing going ? I believe this has been merged about two weeks ago now.

On my side I received the first (issue)[https://github.com/jeancroy/fuzzaldrin-plus/issues/1],
fixed it on master but I'm not sure how to best emit update on this.

Have a nice day.

**Comment by benogle** [comment]
I really like it. I will talk to the team early next week about next steps, and options for future maintenance of the library. Likely, if we were to maintain it, we would want to a code style pass, and general code review.
