### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by donaldwasserman** [atom/autocomplete-plus#590]
Hello - I'm not sure if i'm having problems reading/understanding coffeescript or if the documentation is leading me astray. 

Per the API documentation page, when i call:

```coffee
provider = require 'provider'
module.exports = 
  provide: -> provider
```

the `getSuggestions()` method of my provider file doesn't get called. When I define `provide: -> provider.getSuggestions()` I get a console.log warning `Provider object not valid`. My object looks like `{text: 'foo', displayText: 'bar'}`

I think something is missing from the documentation or I'm missing some sort of coffeescript concept...

**Comment by benogle** [comment]
Do you have a file called `povider`? Shouldnt it be `require './povider'`? Can you point me to a repo where it isnt working?

**Comment by donaldwasserman** [comment]
Thanks for getting back to me so quickly.

Sorry, the `require` was a typo on my part. I narrowed it down to a reproduceable example here: https://github.com/donaldwasserman/atom-ember-author-kit/tree/example

The error I'm getting (v1.0.19) is generated from `lib/provider-manager.js` line  264.

It seems like either the documentation or I am just missing something painfully obvious here...(The smart money would be on me being the culprit.) 

Thanks again.

**Comment by thomasjo** [comment]
@donaldwasserman If you read the documentation super-carefully, especially the part describing [registering a provider](https://github.com/atom/autocomplete-plus/wiki/Provider-API#registering-your-provider-with-autocomplete), you'll see that you're supposed to return a provider object in the registration (aka the service provider implementation). Hence, change your service provider implementation to this

```coffee
provider = require './provider'

module.exports =
  provide: -> provider
```

Which is basically what you had in the beginning (except for missing `./` path prefix), so you were basically doing the right thing in your initial implementation.

Also, I noticed you had both `provider.js` and `provider.coffee`--you should settle on only one since it can be confusing what is resolved when doing `require './provider'` (I believe the JS file will win).

**Comment by donaldwasserman** [comment]
Thanks both of you for taking a look at this --- sadly I realized I had a typo in my `selector` object. 

This is a really neat project and it's getting pretty close to replacing Intellij's IDE for me.

**Comment by MggMuggins** [comment]
I'm having a similar issue: https://github.com/MggMuggins/d-struct
I'm sure the Scope Selector is not the problem, because it works for the blacklist. I've tried all kinds of things, but autocomplete+ is giving me exactly 0 debugging info or output of any kind that I can find to try and help me figure out what the issue is. I have pretty much no experience with CoffeeScript/JavaScript, although I can program fine in other languages. Anybody have any advice?

**Comment by MggMuggins** [comment]
@thomasjo I added that to the API docs. Having it there would have saved me about five hours of looking before I found this issue. Thanks for making that clear though, it did help.
