### ISSUE TITLE
Suggestion should not be shown if full phrase is already typed out

### ISSUE THREAD

**Issue by drewthepooh** [atom/autocomplete-plus#618]
For example, if I type "full_suggestion" the suggestion box should no longer show once I reach the end of the word. Instead it shows "full_suggestion" with the suggestion "full_suggestion" underneath, which is unnecessary and adds clutter

![screen shot 2015-11-18 at 8 43 23 pm](https://cloud.githubusercontent.com/assets/3978031/11262523/0d2ad7d2-8e35-11e5-9db9-0d355261323e.png)

**Comment by prismatica** [comment]
:+1:

**Comment by drewthepooh** [comment]
If there's some configuration option I'm missing please let me know. This seems like very odd behavior though.

**Comment by benogle** [comment]
This has been what you request in the past. I suppose, given that both sides of this generate issues, it could be an option. For now, though, I am inclined to keep it at the current behavior because it is more straightforward. 

The original issue: https://github.com/atom/autocomplete-plus/issues/504, and the PR implementing it: https://github.com/atom/autocomplete-plus/pull/547.

The commit reverting it: https://github.com/atom/autocomplete-plus/commit/0df1c8ba0f4b6d0d5c00f823041a5f32cd9717a4

It was reverted because it was confusing. See https://github.com/atom/autocomplete-snippets/issues/58, https://github.com/atom/atom/issues/8353

**Comment by drewthepooh** [comment]
@benogle thanks for your response. It seems like the behavior is only problematic in the case of snippets.

Sublime text solves this by exhibiting different behavior for autocomplete vs. snippets (see below). This seems like a solution that satisfies all parties. Could we do the same?

![screen shot 2015-11-22 at 12 07 33 pm](https://cloud.githubusercontent.com/assets/3978031/11325997/b3f17f9c-9111-11e5-90e1-a5a80cdcd231.png)

![screen shot 2015-11-22 at 12 09 04 pm](https://cloud.githubusercontent.com/assets/3978031/11326004/d84351fe-9111-11e5-9da1-85bbb61d55e6.png)

![screen shot 2015-11-22 at 12 09 26 pm](https://cloud.githubusercontent.com/assets/3978031/11326008/e7b23448-9111-11e5-84c0-d001d9ea6d7b.png)

Side note: I don't think we should only hide the item if the suggestion list contains one entry. We should always hide a fully typed out item (if it is not a snippet), even if the list contains several entries.
