### ISSUE TITLE
Default completions

### ISSUE THREAD

**Issue by ncammarata** [atom/autocomplete-plus#631]
What would it take to have this kind of interface?

https://vimeo.com/36579366#t=340s. 

For my application, there are a number of defaults I would like to give them, and as they change their selected suggestion, they can see how they look.

**Comment by lee-dohm** [comment]
You can already see something similar to this in the [markdown-preview package](https://atom.io/packages/markdown-preview). The preview updates as the source text is updated.

The next step would be for the currently highlighted completion to change the source text without being selected yet. Any completions would also need to supply default parameters that make sense so that something meaningful is displayed.

Of course, all of this would only be possible for things that have a meaningful preview.

**Comment by steelbrain** [comment]
Should be closed in favor of https://github.com/atom/autocomplete-plus/issues/656
