### ISSUE TITLE
Queue enter key during autocompletion

### ISSUE THREAD

**Issue by chenglou** [atom/autocomplete-plus#649]
If I type too fast and press enter to confirm (e.g. I'm confident in the result because it's a snippet) before the autocomplete has time to show, nothing is auto completed. Is there a way to queue the confirmation after the last keystroke?

**Comment by lee-dohm** [comment]
You can adjust the "Delay Before Suggestions Are Shown" setting:

<img width="736" alt="screen shot 2016-01-13 at 11 44 07 am" src="https://cloud.githubusercontent.com/assets/1038121/12305795/53c8d932-b9eb-11e5-858e-a74c8b037983.png">

:rotating_light: But as the setting explanation says, this can have significant performance implications. Use with caution. :rotating_light:

**Comment by chenglou** [comment]
The delay doesn't affect the fact that it's queued (probably [here](https://github.com/atom/autocomplete-plus/blob/b5648fd5423e137b2b99de733c50c436c0539259/lib/autocomplete-manager.coffee#L430)?). Even adjusting it to 0 doesn't work. As long as some providers take time to reply there'll be a delay.

**Comment by chenglou** [comment]
Ping =)

**Comment by lee-dohm** [comment]
I understand that you want this functionality for you. We have to consider how it will affect every other person that will use the feature. What you're essentially asking for is for people's keystrokes to be held hostage until all providers return with suggestions. The reason there is a typing delay is so that if people just want to type and ignore the autocomplete suggestions they can. Your requested feature would change that so that they would have to wait for the autocomplete suggestions, escape out of them and continue on. This is an untenable scenario for many, many users of autocomplete-plus.

In my opinion, even as an option, it would be too frustrating and confusing to include for the vast majority of users.

**Comment by chenglou** [comment]
That's not what I'm proposing. No keystrokes is held hostage. You keep typing on and only the enter key (or whatever commit key) is queued. It has nothing to do with tweaking the typing delay as I've mentioned.

What this does is to make the autocomplete commit action deterministic. Right now if you type `rn <enter>` you have no idea if you're gonna get e.g. `return` or `random` because the providers race against each other, and depending on which one finishes and when you pressed enter, you'll get either result. Even the snippet <tab> autocompletion is affected by this.

**Comment by lee-dohm** [comment]
Right now if I type `rn <enter>` I know I'm going to get `rn\n`, which is what I want. I also know that if I type `rn <pause until I can see the selections><enter>` I will also get what I want. Your suggestion to queue the <kbd>Enter</kbd> is holding my typing hostage because I won't get the newline that I expect to get when I press <kbd>Enter</kbd>.

If you know exactly what you want and don't want to wait for the autocomplete, you can create a snippet, type the activation prefix of the snippet and press <kbd>Tab</kbd>. It will allow you to keep typing as fast as you want. You could even reprogram Atom to use <kbd>Enter</kbd> as the activation key for snippets and that would get you what you want.

Thanks again for all your feedback. The way you're suggesting for the autocomplete system to work is not how we envision it should work.
