### ISSUE TITLE
Consume suffix while typing

### ISSUE THREAD

**Issue by abyss7** [atom/autocomplete-plus#654]
If I invoke auto-completion in a middle of some word (or at the beginning) and type symbols, then the symbols expand the completion prefix. It would be nice, if the new symbols match the suffix, then they don't get printed - but the cursor just gets moved.

Hope I made a good explanation.

**Comment by lee-dohm** [comment]
So you're suggesting that if I have:

```
t|st
```

where the `|` is the position of the cursor. And I have a suggestion for `te` that expands to `testing`. That if I type <kbd>E</kbd><kbd>Tab</kbd>, you want the contents of the file and position of the cursor to be:

```
testing|
```

Not:

```
testing|st
```

Is that correct?

**Comment by abyss7** [comment]
Not exactly, but what you wrote strongly correlates. If I have:

    t|est

where `|` is the cursor. And when I type <kbd>e</kbd> **or** <kbd>→</kbd>, I want the suggestions to  narrow to prefix `te` while I have:

    te|st

Instead of now being in case of <kbd>e</kbd>:

    te|est

or suggestion being closed in case of <kbd>→</kbd>.

So further enhancements on suffix "eating" are good too - as separate issues.

**Comment by lee-dohm** [comment]
I would be :-1: on this change because after your suggestion is implemented, Atom wouldn't obey my typing. Let's say that I have an `fe` snippet and I'm typing the word `feeble` but I make a typo and it comes out `feble`. When I go back to correct it, putting the cursor here:

```
f|eble
```

And press <kbd>E</kbd>, Atom apparently ignores my keystroke unless I'm watching closely and notice that my cursor has moved:

```
fe|ble
```

Then I press another <kbd>E</kbd> and things work?

```
fee|ble
```

That would be very confusing for many people.

**Comment by abyss7** [comment]
I understand your point. And what about <kbd>→</kbd>? - It's a good feature from QtCreator.

**Comment by lee-dohm** [comment]
I've never used QtCreator, so I'm not sure what you mean.

**Comment by skylize** [comment]
In the case of  → , I could see the value in continuing to providing suggestions based on text to the left of the cursor. On the other hand, do we really want autocomplete to always be popping up as we move around the file with arrow keys?
