### ISSUE TITLE
confirm key doesn't work in html attributes

### ISSUE THREAD

**Issue by ajoslin103** [atom/autocomplete-plus#687]
When editing an index.html file and trying to use autocomplete within an html attribute the confirm key sometimes cancels the confirm and sometimes is entered into the attribute

Try changing the src attribute script tag -- the enter key is inserted instead of the selected autocomplete value

**Comment by lmartins** [comment]
Same here, I had autocomplete configured to complete with both enter or tab and both keys now just do the default output and not autocomplete confirmation. This happens with latest releases of both the normal and beta channels.

**Comment by lmartins** [comment]
Sorry for repeating myself but any chance we can get some feedback on this issue soon. For anyone relying on autocomplete this is quite a significant issue.

**Comment by lee-dohm** [comment]
Please give us specific steps to reproduce the problem.

**Comment by lmartins** [comment]
Hi @lee-dohm 
Not really sure what info might be added here.
Here's what I see:

* While typing I see AutoComplete's suggestions
* Try to press Enter or Tab to confirm one of the suggestions
* I do see Autocomplete confirmation in the Key Binding Resolver
* Still nothing happens in the editor

**Comment by lee-dohm** [comment]
@lmartins I can't reproduce this issue based on the steps you provided. Every time I press the confirmation key, the right thing happens. Please give a step-by-step account of how you can make this happen. See the [How Do I Write a (Good) Bug Report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) section of the CONTRIBUTING guide for suggestions.

**Comment by jcroughton** [comment]
I think this is similar to what I believed to be expected behaviour (based on Sublime Text).

When starting an HTML tag we perhaps expect the completion key (tab/return) to close said tag e.g.

<h2[completionkey] = <h2></h2>

However Atom thinks / works differently, whereby it's possible you may want to add attributes to the given tag i.e.

<h2 class=""

Thus the completion key is not closing the tag and is waiting for you to potentially start type an attribute name (hit space after [compeltionkey] to see autocomplete start suggesting attributes names for the given tag).

A "fix" / work-around for me was to use the autoclose-html plugin. You still need to provide the closing bracket to the opening html tag but it then closes the tag for you. i.e.

<h2> = <h2></h2>

**Comment by jcroughton** [comment]
I think this is similar to what I believed to be expected behaviour (based on Sublime Text).

When starting an HTML tag we perhaps expect the completion key (tab/return) to close said tag e.g.

`<h2[completionkey]` becomes `<h2></h2>`

However Atom thinks / works differently, whereby it's possible you may want to add attributes to the given tag i.e.

`<h2 class=""`

Thus the completion key is not closing the tag and is waiting for you to potentially start type an attribute name (hit space after [compeltionkey] to see autocomplete start suggesting attributes names for the given tag).

A "fix" / work-around for me was to use the autoclose-html plugin. You still need to provide the closing bracket to the opening html tag but it then closes the tag for you. i.e.

`<h2>` becomes `<h2></h2>`

**Comment by lmartins** [comment]
@jcroughton My case was different `h2` would stay h2 no matter what. But i've found that resetting my keybindings solved the problem. Somehow there was a problem there that only manifested itself after the latest Atom's update. Working great now for me.

**Comment by lee-dohm** [comment]
I'm glad to hear that things are working for you now @lmartins.

@ajoslin103 do you have any updates?

**Comment by ajoslin103** [comment]
I can not reproduce the problem anymore, so I'm good -- thanks!
