### ISSUE TITLE
Possible to deactivate provider?

### ISSUE THREAD

**Issue by jgoley** [atom/autocomplete-plus#734]
I'm trying to deactivate or prevent my provider from being added to autocomplete-plus based on a condition in the `activate` method (that requires an asynchronous response - checking to see if a folder exists in the project).
I've managed to half implement this by calling `dispose` wherein `getSuggestions` is set to `null`, but this leads to a console error: `Provider MeteorPackagesProvider is not valid`.
Is it possible to deactivate my provider after its been added to autocomplete-plus?

**Comment by lee-dohm** [comment]
Yes, it is possible to deactivate a provider the same as any other package: `atom.packages.deactivatePackage()`. Of course, if you do that ... then your package can't have code to reactivate itself ... because it isn't loaded anymore. The proper way to do this is when your package is asked for suggestions, it should check to see if the project is applicable and decide then.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

**Comment by jgoley** [comment]
Thanks @lee-dohm!
