### ISSUE TITLE
doesn't have colorful symbol 

### ISSUE THREAD

**Issue by DimmuSun** [atom/autocomplete-plus#759]
I use windows,the plugin seems to do the work partielly,
just have this
![image](https://cloud.githubusercontent.com/assets/21170420/18026290/45b502da-6c74-11e6-8c5a-cdffb4ada34d.png)
but not this
![image](https://cloud.githubusercontent.com/assets/21170420/18026298/7d75ebb2-6c74-11e6-8b20-70b89a13c72e.png)

**Comment by DimmuSun** [comment]
it doesn't show color symbol of func ,method,and other ,why?

**Comment by 50Wliu** [comment]
This is because you don't have any file buffers open (or any text in the untitled tab) for autocomplete-plus to get autocompletions from in your first example.  In addition, you most likely don't have a dedicated autocompletion package for Python installed.

https://atom.io/packages/search?q=python+autocomplete
