### ISSUE TITLE
Atom autocomplete-plus isn't working at all

### ISSUE THREAD

**Issue by Empirio808** [atom/autocomplete-plus#816]
I just downloaded Atom, simply giving it a go and I noticed none of the tags autocomplete. Tried typing html and TAB and.. nothing. No matter what I attempt to type, no autocomplete.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
