### ISSUE TITLE
Why the auto suggestion not shows accurately

### ISSUE THREAD

**Issue by boosters** [atom/autocomplete-plus#817]
I'm coming from phpstorm to Atom for JS, Ajax, etc. but I am not happy with the autocomplete suggestion. Right now I am working on Ajax, if I write code like xhr.onreadystatechange, it doesn't display any suggestion for the onreadystatechange, check the below screenshot

![](http://image.prntscr.com/image/b72ec97876be44c9b3b47e467b6334ff.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
