### ISSUE TITLE
Autocomplete for *.md does not work.

### ISSUE THREAD

**Issue by Josca** [atom/autocomplete-plus#822]
### Description

Autocomplete for markdown files does not work. How to enable autocomplete for ALL files? I replaced 'File Blacklist' filed with value '*.ttt' to disable default value [*.md, *.txt]. When I rename my .md file with .py extension, autocomplete works.

### Steps to Reproduce

1. Modify autocomplete-plus settings: File Blacklist: *.ttt.
2. Create test.md.
3. Write string 'hello' to the first line.
4. Try to write 'hel' to the second line - autocomplete does not work.
5. Rename file to test.py
6. Try to write 'hel' to the second line - autocomplete works.

How to disable default 'File Blacklist' value without putting dummy '*.ttt' extension?

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be _completely_ filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
