### ISSUE TITLE
It doesn't work with snippets in Markdown file.

### ISSUE THREAD

**Issue by NanerLee** [atom/autocomplete-plus#833]
In my own snippets.cson , I create a new snippet :

```
'.source.md':

  'Read More':
    'prefix': 'more'
    'body': '<!--more-->\n'
```

But when I input *more*, it doesn't give me advice. And the file blacklist is default.

I don't know this problem is belong which package - *autocomplete-plus* or *autocomplete-snippets*

**Comment by rsese** [comment]
Thanks for reaching out!  Can you post this question in the [Atom message board](https://discuss.atom.io)?  I'll keep an eye out for your post and see if I can help.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions or [don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
