### ISSUE TITLE
SUGGESTION - have an option to disable taking suggestions from notes

### ISSUE THREAD

**Issue by lukipav** [atom/autocomplete-plus#847]
It would be good if, for example, html notes wouldn't get taken as code because then when I write actual code I get suggestions for things i wrote in the notes.

.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
