### ISSUE TITLE
Auto Fill Wrong Word

### ISSUE THREAD

**Issue by Kylescottw** [atom/autocomplete-plus#854]
Hello,
It seems that atom must have picked up on a wrongly typed word, and now when I type "component" it will replace it with "componenent". can anyone help suggest a fix? I'm considering uninstalling atom then re installing it to refresh the memory.

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---
As a side note, what you are describing sounds like OS-level spelling correction (I suspect you might be running macOS). At the very least it has nothing to do with autocomplete-plus, nor any other bundled Atom package.
