### ISSUE TITLE
Emmet & Autocomplete plus issue

### ISSUE THREAD

**Issue by knitevision1** [atom/autocomplete-plus#86]
Hello.

So, basically, in ST2 Emmet & Default ST Autocomplete work fine.

When I switched to Atom, I installed your package and tried to get it work with Emmet, but failed.

Steps to reproduce

1) Install Emmet & Autocomplete plus
2) Type just a plain word in the text starting from any tag, for example: h2test
3) Try to create an h2 tag using "h2 + tab" and you will get "h2test"

While in the Sublime Text the result would be the created markup for the h2 tag, in your Autocomplete it results in "h2test" appeared instead of the tag.

Is there something can be done with it?

**Update**

Partially solved with _Auto Activation Delay_

**Comment by matthew-b-payne** [comment]
Sublime Text also uses tab for Emmet and autocomplete expansion, yet the two seem to work in harmony together.

**Comment by jordanbtucker** [comment]
If you want to use <kbd>Tab</kbd> with Autocomplete *and* Emmet, this is what I do.

Install [autocomplete-plus][acp] and [autocomplete-snippets][acps] (and whatever other [autocomplete-plus provider packages][acppp] you want):

    apm install autocomplete-plus autocomplete-snippets

Next, edit your keymap.cson file (**File > Open Your Keymap**) and paste this at the bottom:

```cson
# Stop emmet from hijacking tab from snippets and autocomplete
'atom-text-editor.autocomplete-active[data-grammar="text html basic"]:not([mini]), atom-text-editor[data-grammar~="jade"]:not([mini]), atom-text-editor[data-grammar~="css"]:not([mini]), atom-text-editor[data-grammar~="sass"]:not([mini])':
  'tab': 'autocomplete-plus:confirm'
```

This allows you to still use <kbd>Tab</kbd> with Emmet, but only when the autocomplete popup is not open.

- If you start typing, and autocomplete pops up, you can press <kbd>Tab</kbd> for autocomplete.
- If autocomplete doesn't pop up (because there are no matches), you can press <kbd>Tab</kbd> and get an Emmet expansion.
- If autocomplete does pop up, but you want to use an Emmet expansion, you can press <kbd>Esc</kbd> to close the autocomplete popup and then press <kbd>Tab</kbd> for an Emmet expansion.

The reason you need to install autocomplete-snippets is because Emmet takes precedence over snippets, but if you have an autocomplete popup open and this keymapping in place, then the snippet will take precedence.

The best of both worlds.

[acp]: https://atom.io/packages/autocomplete-plus
[acps]: https://atom.io/packages/autocomplete-snippets
[acppp]: https://github.com/atom-community/autocomplete-plus/wiki/Autocomplete-Providers

**Comment by caillou** [comment]
@jordanbtucker :tada: Your setup totally does the trick for me. Thank you!

**Comment by joefitzgerald** [comment]
@jordanbtucker is clearly a keymap maestro :wink:. Nice solution!

**Comment by jordanbtucker** [comment]
Thanks, guys. I just updated my comment with some caveats regarding snippet tab stops.

I've actually posted this solution in a few places for everyone's benefit, but keeping them up to date is problematic. For future updates, please subscribe to [emmet-atom issue #225][em225].

[em225]: https://github.com/emmetio/emmet-atom/issues/225#issuecomment-82669798

**Comment by joefitzgerald** [comment]
Perhaps this would be helpful info for https://github.com/atom-community/autocomplete-plus/wiki. We could have a `keymap` article?

**Comment by bbugh** [comment]
This was still a problem for me a year later, and @jordanbtucker's fix worked for me. Thanks for that! It was driving me mad.

**Comment by jtlevy** [comment]
@jordanbtucker OUTSTANDING!!

**Comment by freshyill** [comment]
Maybe it was a recent change to something else in Atom, but this seems to have broke using tab just to indent. Nothing at all would happen if I tried to indent. The solution for me was just to add `.autocomplete-active` to the classes where it was missing.

`'atom-text-editor.autocomplete-active[data-grammar="text html basic"]:not([mini]), atom-text-editor.autocomplete-active[data-grammar~="jade"]:not([mini]), atom-text-editor.autocomplete-active[data-grammar~="css"]:not([mini]), atom-text-editor.autocomplete-active[data-grammar~="sass"]:not([mini])':
  'tab': 'autocomplete-plus:confirm`

**Comment by corysimmons** [comment]
@freshyill I can confirm this. Any keymap I make that uses tabs breaks tabs for everything else.

**Comment by greg-hub** [comment]
@jordanbtucker worked a treat! 

Thanks

**Comment by plonko** [comment]
Anyone got an updated complete tab config I can copy-pasta? 
I'm not getting the desired behaviour and all these :nots are making my eyes fuzzy. :)

**Comment by ModernWebService** [comment]
I am not sure how, since I believe i tried this keymapping several times but after Sublime Text 3 has started to freeze and fail to quit on my computers lately, I found this post and copied this keymapping and now expands elements with classes and does not hijack your tab causing you to have to clcik cmd+[ or ctrl+[ to tab a line/indent [](https://github.com/emmetio/emmet-atom/issues/491)

**Comment by SndrL** [comment]
I ran into this (frustrating) problem too. jordanbtucker's fix does the trick! Thank you!

**Comment by hungpro276** [comment]
@jordanbtucker works greatly in 2018, thank you <3
