### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TonyRuQusSCarbetta** [atom/autocomplete-plus#878]
Hello,
    When I type anthing in atom I am recieving no auto complete suggestions.  The text doesn't change color at all.  It's as if I didn't download the package at all.  How can I get this to work?

**Comment by rsese** [comment]
Thanks for reaching out @TonyRuQusSCarbetta - can you please either open a new issue with the template filled out or edit your issue body to include the template information?  In particular, please let us know the results of going through the `Prerequisites` section (e.g. do you have the same problem in safe mode, have you gone through the debugging section of the flight manual, etc.).  Also, the `Versions` section asks for the version of Atom you're running and what operating system as well so please share that information as well.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by rsese** [comment]
Oh also, for the steps to reproduce section, please let us know what type of file you're editing (e.g. JavaScript, Markdown, etc.), what text you enter, and what auto-completion you expect.

**Comment by TonyRuQusSCarbetta** [comment]
Sorry for the late response.  I got it to work.  I was totally new at the time.  I just needed to save the file first with .html at the end.   Thank you for your response

**Comment by rsese** [comment]
Ahhh ok, glad to hear you have things sorted out :+1:
