### ISSUE TITLE
Autocomplete to "// HACK:"

### ISSUE THREAD

**Issue by FlatlineTV** [atom/autocomplete-plus#889]
Why is autocomplete listing HACK instead of height or anything else as priority?

How do I disable/blacklist this?

![nblwtme](https://user-images.githubusercontent.com/13840075/30477149-07fd0638-99c1-11e7-9d6a-deaa3d945919.gif)

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Hack in the suggestion list is a snippet. You can disable the `autocomplete-snippets` package to remove it from the suggestion list.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
