### ISSUE TITLE
Prioritizing snippets in autocomplete suggestions

### ISSUE THREAD

**Issue by saadq** [atom/autocomplete-plus#946]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When there are autocomplete options available, they often push the user snippets suggetsions near the bottom. Is there any way to always keep user snippets at the top of the autocomplete suggestion?

### Steps to Reproduce

 Have a JavaScript variable called `close` and have a `cl` snippet for `console.log`. <kbd>cl</kbd> + <kbd>Tab</kbd> will autocomplete to `close`.

**Expected behavior:** [What you expect to happen]
<kbd>cl</kbd> + <kbd>Tab</kbd> will autocomplete to `console.log`.

**Actual behavior:** [What actually happens]
<kbd>cl</kbd> + <kbd>Tab</kbd> will autocomplete to `close`.

**Reproduces how often:** [What percentage of the time does it reproduce?]
N/A

### Versions

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.12
git 2.10.1

OS: macOS Sierra Version 10.12.6

**Comment by Aerijo** [comment]
I'm not getting this with the subsequence provider. I have:
```cson
# snippets.cson
'.source.js':
  'cl':
      prefix: 'cl'
      body: 'console.log($1);$2'
```
and the result is:
<img width="272" alt="screen shot 2018-01-17 at 8 35 29 am" src="https://user-images.githubusercontent.com/22167388/35015732-67fd49d8-fb61-11e7-9a3d-89dc81276431.png">

You will need to provide more information on how to reproduce, what settings you have, the provider you're using; something that can be used to consistently reproduce the issue.

**Comment by zmike** [comment]
I have this same behavior in C. I'm using autocomplete-snippets package and my snippets do not work if autocomplete+ is enabled; it just uses a random symbol instead of the snippet.

I'm new to atom, so I don't know what other info I can provide.

**Comment by Aerijo** [comment]
@saadq @zmike sorry, but until someone provides a way to consistently reproduce the error from scratch, nobody can help much. As I showed, I do not get the same behaviour when following the provided steps to reproduce.

A process that I can follow, that starts by opening Atom in safe mode, is what you need to provide. Right now, when I do the following steps, I get the same result I posted above

1. Open Atom in safe mode
2. In the `snippets.cson` file, delete everything and paste the following
```cson
'.source.js':
  'Console log':
    'prefix': 'cl'
    'body': 'console.log($1);'
```
3. Open a new blank file. It does not need to be saved.
4. Paste the following text
```js
var close = "close"
```
5. On a new line, type `cl`
6. Observe that the `cl` snippet is the first option, and pressing `tab` expands it as expected.

There are 101 things that can be happening with all the community packages you have installed. Using safe mode ensures that everybody is using (mostly) the same setup when trying to debug issues.

@zmike there is a little confusion between what the `autocomplete-plus` and `snippets` packages do (the lack of an explanation in the README.md on both doesn't help). I try to explain the difference [here](https://gist.github.com/Aerijo/5b9522530715e5be6e89fc012e9a72a8#some-general-notes), but basically snippets work when you disable that `autocomplete-plus` option because `snippets` was always using `tab` to complete snippets, but `autocomplete-plus` was overriding it when the suggestions were shown.

**Comment by zmike** [comment]
I tried using my setup with safe mode enabled and snippet completion worked as expected. I then started up atom normally and reenabled my small number of community packages one by one until the issue was reproduced.

When I enabled the ide-cquery package, I began to get unpredictable results and snippets were no longer functional, so I've uninstalled that package and now everything is working well. Thanks for providing extra info which helped me to at least resolve the issue with my setup; I would expect that a similar package is causing the original issue as well.

This is a bit unrelated, but is there a way to have the keystroke tooltip only show items containing the typed string? As an example, if I type "abc" and I have a variable named "ABABAB_CDCDCD" then it will show this variable on the list when I would prefer that it only show something containing the string "abc".

**Comment by saadq** [comment]
Sorry for the late response. I will try to see if I can create a minimal, reproducible example, but I imagine my issue is similar to @zmike and the issue might just be coming from `atom-ide-ui` and `ide-flowtype` putting their autocomplete suggestions at the top.

**Comment by zmike** [comment]
@saadq I am also using atom-ide-ui, but it seems that by itself it does not cause this issue.

**Comment by saadq** [comment]
Yeah, I don't believe `atom-ide-ui` gives any autocomplete by itself, it needs to be paired with an `ide-*` package. But it may still be the cause of the issue (for example, the `ide-*` package feeds `atom-ide-ui` package the autocompletions and then `atom-ide-ui` feeds them to `autocomplete-plus`. I don't know if that's how it works or not, but just something to consider.

**Comment by saadq** [comment]
I am going to close this issue here as it isn't really a problem with `autocomplete-plus` itself. In [this issue](https://github.com/facebook-atom/atom-ide-ui/issues/157) for `ide-flowtype`, one of the authors mentioned that they set the priority for autocomplete [here](https://github.com/flowtype/ide-flowtype/blob/master/lib/main.js#L122). 

A good idea might be to try to send a pull request or open an issue in the [Atom `snippets` package](https://github.com/atom/snippets) and see if they would be interested in adding a configurable option that lets their priority always be the highest.
