### ISSUE TITLE
Question: What are the difference between autocomplete-plus v2 and v4?

### ISSUE THREAD

**Issue by jonyeezs** [atom/autocomplete-plus#947]
Hi I'm planning to upgrade my provider from v2 to v4.

Are there any breaking changes I should be aware of? I cannot find any documentation.

**Comment by nathansobo** [comment]
We simplified our handling of prefixes in version 4.

Prior to v4, this package would determine prefixes via a fixed regular expression, potentially allowing symbolic characters. In 4, *only* word characters are included in the provided prefix, and we consult the language settings to determine what constitutes a word character. All alphanumeric characters plus common symbols are included unless explicitly black-listed in the `editor.nonWordCharacters` setting for the current language. You can treat some characters as word characters only for the purposes of autocomplete in the `autocomplete.extraWordCharacters` setting.

Also in v4, we always default the completion prefix to be the prefix passed to your provider unless you specify otherwise. Previously there was some complicated logic about whether or not to default the completion prefix due to non-word characters being sometimes included in the prefix.

Hope this helps.
