### ISSUE TITLE
autocomplete-plus always show Warning Deprecation

### ISSUE THREAD

**Issue by cubiczx** [atom/autocomplete-plus#985]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

atom core (1 deprecation)
Autocomplete provider 'ClassProvider(undefined)' returns suggestions with a prefix attribute. The prefix attribute is now replacementPrefix and is optional. See https://github.com/atom/autocomplete-plus/wiki/Provider-API
AutocompleteManager.deprecateForSuggestion - <embedded>:42623:18
providerPromises.push.Promise.resolve.then.providerSuggestions - <embedded>:42488:40
<unknown> - null:null:null

in `atom --safe` not fail

### Steps to Reproduce

1. Open Atom
2. Open warning deprecation

**Expected behavior:** Not display deprecation warning

**Actual behavior:** Show a warning deprecation

**Reproduces how often:** Always

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
`atom --version`
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

`apm --version` 
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.12
git 2.7.4

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!

> in atom --safe not fail

Because you're not seeing this issue in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
