### ISSUE TITLE
Confusing naming for settings of "Keymap For Confirming A Suggestion"

### ISSUE THREAD

**Issue by jfp42** [atom/autocomplete-plus#999]
The name of the setting for "Keymap For Confirming A Suggestion" : "tab and enter" is confusing, it should be "tab or enter".

"tab and enter" means "tab then enter", whereas the actual behaviour is "tab or enter".

**Comment by thomasjo** [comment]
Thanks for the feedback! :sparkles: 

Since changing the name of the option would cause a breaking change, we will need a very convincing argument for changing it. Any confusion can be addressed by documentation. Since we're not likely to be changing this anytime soon, I'm going to close the issue.

For future issues, please fill in the (mandatory) issue template. Thanks :bowing_man:
